// GENERATED by assets/make_art.py - do not edit
#pragma once
#include <stdint.h>

#define NTILES 214
#define IMG_COUNT 798
#define F_SOLID 1
#define F_BUILDING 2
#define F_TREE 4
#define F_WATER 8
#define F_ROAD 16
#define F_TALL 32
#define F_SPRAY 64

#define TILE_GRASS0 0
#define TILE_GRASS1 1
#define TILE_GRASS2 2
#define TILE_DIRT0 3
#define TILE_DIRT1 4
#define TILE_SCRUB0 5
#define TILE_SCRUB1 6
#define TILE_SAND0 7
#define TILE_SAND1 8
#define TILE_WETSAND 9
#define TILE_SIDEWALK0 10
#define TILE_SIDEWALK1 11
#define TILE_PLAZA0 12
#define TILE_PLAZA1 13
#define TILE_STAR_WALK 14
#define TILE_WOOD0 15
#define TILE_WOOD1 16
#define TILE_CONCRETE0 17
#define TILE_CONCRETE1 18
#define TILE_COURT0 19
#define TILE_SPRAY_PAD 20
#define TILE_ROAD 21
#define TILE_ROAD1 22
#define TILE_ROAD2 23
#define TILE_ROAD_HY_B 24
#define TILE_ROAD_HY_T 25
#define TILE_ROAD_HW_B 26
#define TILE_ROAD_HW_T 27
#define TILE_ROAD_VY_R 28
#define TILE_ROAD_VY_L 29
#define TILE_ROAD_VW_R 30
#define TILE_ROAD_VW_L 31
#define TILE_CW_V 32
#define TILE_CW_H 33
#define TILE_PARKING_V 34
#define TILE_PARKING_H 35
#define TILE_FW 36
#define TILE_FW_DASH_L 37
#define TILE_FW_DASH_R 38
#define TILE_FW_EDGE_L 39
#define TILE_FW_EDGE_R 40
#define TILE_FW_BARRIER 41
#define TILE_FW_EDGE_T 42
#define TILE_FW_EDGE_B 43
#define TILE_FW_DASH_T 44
#define TILE_FW_DASH_B 45
#define TILE_FW_BARRIER_H 46
#define TILE_RAIL_H 47
#define TILE_RAIL_V 48
#define TILE_RAIL_X_V 49
#define TILE_RAIL_X_H 50
#define TILE_RUNWAY 51
#define TILE_RUNWAY_DASH 52
#define TILE_OCEAN0 53
#define TILE_OCEAN1 54
#define TILE_WATER0 55
#define TILE_WATER1 56
#define TILE_STREAM 57
#define TILE_POOL0 58
#define TILE_ROOF_GRAY0 59
#define TILE_ROOF_GRAY1 60
#define TILE_ROOF_GRAY2 61
#define TILE_ROOF_GRAY3 62
#define TILE_ROOF_TAN0 63
#define TILE_ROOF_TAN1 64
#define TILE_ROOF_TAN2 65
#define TILE_ROOF_TAN3 66
#define TILE_ROOF_BROWN0 67
#define TILE_ROOF_BROWN1 68
#define TILE_ROOF_BROWN2 69
#define TILE_ROOF_BROWN3 70
#define TILE_ROOF_RED0 71
#define TILE_ROOF_RED1 72
#define TILE_ROOF_RED2 73
#define TILE_ROOF_RED3 74
#define TILE_ROOF_BLUE0 75
#define TILE_ROOF_BLUE1 76
#define TILE_ROOF_BLUE2 77
#define TILE_ROOF_BLUE3 78
#define TILE_ROOF_TEAL0 79
#define TILE_ROOF_TEAL1 80
#define TILE_ROOF_TEAL2 81
#define TILE_ROOF_TEAL3 82
#define TILE_ROOF_WHITE0 83
#define TILE_ROOF_WHITE1 84
#define TILE_ROOF_WHITE2 85
#define TILE_ROOF_WHITE3 86
#define TILE_ROOF_DARK0 87
#define TILE_ROOF_DARK1 88
#define TILE_ROOF_DARK2 89
#define TILE_ROOF_DARK3 90
#define TILE_ROOF_GREEN0 91
#define TILE_ROOF_GREEN1 92
#define TILE_ROOF_GREEN2 93
#define TILE_ROOF_GREEN3 94
#define TILE_ROOF_ORANGE0 95
#define TILE_ROOF_ORANGE1 96
#define TILE_ROOF_ORANGE2 97
#define TILE_ROOF_ORANGE3 98
#define TILE_ROOF_THEATRE 99
#define TILE_ROOF_GARAGE 100
#define TILE_ROOF_POLICE 101
#define TILE_ROOF_STATION 102
#define TILE_STAND 103
#define TILE_HOSP_0 104
#define TILE_HOSP_1 105
#define TILE_HOSP_2 106
#define TILE_HOSP_3 107
#define TILE_HOSP_4 108
#define TILE_HOSP_5 109
#define TILE_HOSP_6 110
#define TILE_HOSP_7 111
#define TILE_HOSP_8 112
#define TILE_PAD_0 113
#define TILE_PAD_1 114
#define TILE_PAD_2 115
#define TILE_PAD_3 116
#define TILE_PAD_4 117
#define TILE_PAD_5 118
#define TILE_PAD_6 119
#define TILE_PAD_7 120
#define TILE_PAD_8 121
#define TILE_TOWER_GLASS0 122
#define TILE_TOWER_GLASS1 123
#define TILE_TOWER_DARK0 124
#define TILE_TOWER_DARK1 125
#define TILE_TOWER_STONE0 126
#define TILE_TOWER_STONE1 127
#define TILE_OBS_0 128
#define TILE_OBS_1 129
#define TILE_OBS_2 130
#define TILE_OBS_3 131
#define TILE_OBS_4 132
#define TILE_OBS_5 133
#define TILE_OBS_6 134
#define TILE_OBS_7 135
#define TILE_OBS_8 136
#define TILE_FERRIS_0 137
#define TILE_FERRIS_1 138
#define TILE_FERRIS_2 139
#define TILE_FERRIS_3 140
#define TILE_FERRIS_4 141
#define TILE_FERRIS_5 142
#define TILE_FERRIS_6 143
#define TILE_FERRIS_7 144
#define TILE_FERRIS_8 145
#define TILE_FERRIS_9 146
#define TILE_FERRIS_10 147
#define TILE_FERRIS_11 148
#define TILE_FERRIS_12 149
#define TILE_FERRIS_13 150
#define TILE_FERRIS_14 151
#define TILE_FERRIS_15 152
#define TILE_FIELD0 153
#define TILE_FIELD1 154
#define TILE_TRACK 155
#define TILE_TREE0 156
#define TILE_TREE1 157
#define TILE_PALM 158
#define TILE_BUSH 159
#define TILE_HSIGN_0_0 160
#define TILE_HSIGN_0_1 161
#define TILE_HSIGN_0_2 162
#define TILE_HSIGN_0_3 163
#define TILE_HSIGN_0_4 164
#define TILE_HSIGN_0_5 165
#define TILE_HSIGN_0_6 166
#define TILE_HSIGN_0_7 167
#define TILE_HSIGN_0_8 168
#define TILE_HSIGN_0_9 169
#define TILE_HSIGN_0_10 170
#define TILE_HSIGN_0_11 171
#define TILE_HSIGN_0_12 172
#define TILE_HSIGN_0_13 173
#define TILE_HSIGN_0_14 174
#define TILE_HSIGN_0_15 175
#define TILE_HSIGN_0_16 176
#define TILE_HSIGN_0_17 177
#define TILE_HSIGN_1_0 178
#define TILE_HSIGN_1_1 179
#define TILE_HSIGN_1_2 180
#define TILE_HSIGN_1_3 181
#define TILE_HSIGN_1_4 182
#define TILE_HSIGN_1_5 183
#define TILE_HSIGN_1_6 184
#define TILE_HSIGN_1_7 185
#define TILE_HSIGN_1_8 186
#define TILE_HSIGN_1_9 187
#define TILE_HSIGN_1_10 188
#define TILE_HSIGN_1_11 189
#define TILE_HSIGN_1_12 190
#define TILE_HSIGN_1_13 191
#define TILE_HSIGN_1_14 192
#define TILE_HSIGN_1_15 193
#define TILE_HSIGN_1_16 194
#define TILE_HSIGN_1_17 195
#define TILE_HSIGN_2_0 196
#define TILE_HSIGN_2_1 197
#define TILE_HSIGN_2_2 198
#define TILE_HSIGN_2_3 199
#define TILE_HSIGN_2_4 200
#define TILE_HSIGN_2_5 201
#define TILE_HSIGN_2_6 202
#define TILE_HSIGN_2_7 203
#define TILE_HSIGN_2_8 204
#define TILE_HSIGN_2_9 205
#define TILE_HSIGN_2_10 206
#define TILE_HSIGN_2_11 207
#define TILE_HSIGN_2_12 208
#define TILE_HSIGN_2_13 209
#define TILE_HSIGN_2_14 210
#define TILE_HSIGN_2_15 211
#define TILE_HSIGN_2_16 212
#define TILE_HSIGN_2_17 213

#define IMG_EDGE_N 214
#define IMG_EDGE_E 215
#define IMG_EDGE_S 216
#define IMG_EDGE_W 217
#define IMG_CANOPY0 218
#define IMG_CANOPY1 219
#define IMG_PALMTOP 220
#define IMG_SHADOW 221
#define IMG_MINIMAP 797
#define IMG_PLAYER_BASE 334
#define IMG_PLAYER(frame, dir) (IMG_PLAYER_BASE + (frame) * 16 + (dir))
#define DIRS 16
#define WALK_FRAMES 4
#define PED_DIRS 8
#define PED_FRAMES 2

#define NCARVARS 12
#define IMG_CAR_BASE 398
#define IMG_CAR(var, dir) (IMG_CAR_BASE + (var) * 16 + (dir))
__attribute__((unused)) static const uint8_t carvar_model[NCARVARS] = {0,0,1,1,1,2,2,3,4,5,6,7};
#define NPEDTYPES 8
#define IMG_PED_BASE 590
#define IMG_PED(t, f, dir) (IMG_PED_BASE + ((t) * 2 + (f)) * 8 + (dir))
#define IMG_GUN_BASE 222
#define IMG_GUN(w, k) (IMG_GUN_BASE + ((w) - 1) * 16 + (k))
#define IMG_CORPSE_BASE 718
#define IMG_CORPSE(t, k) (IMG_CORPSE_BASE + (t) * 4 + (k))
#define IMG_MUZZLE 750
#define IMG_BULLET 751
#define IMG_SPARK 752
#define IMG_BLOOD_DOT 753
#define IMG_GLOW_RED 754
#define IMG_GLOW_BLUE 755
#define IMG_SHADOW_CAR 756
#define IMG_STAIN0 757
#define IMG_STAIN1 758
#define IMG_STAIN2 759
#define IMG_STAIN3 760
#define IMG_BOOM0 761
#define IMG_BOOM1 762
#define IMG_BOOM2 763
#define IMG_BOOM3 764
#define IMG_BOOM4 765
#define IMG_BOOM5 766
#define IMG_SMOKE0 767
#define IMG_SMOKE1 768
#define IMG_SMOKE2 769
#define IMG_FIRE0 770
#define IMG_FIRE1 771
#define IMG_FIRE2 772
#define IMG_PK_HEALTH 773
#define IMG_PK_ARMOR 774
#define IMG_PK_PISTOL 775
#define IMG_PK_SMG 776
#define IMG_PK_SHOTGUN 777
#define IMG_PK_CASH 778
#define IMG_PK_RIFLE 779
#define IMG_PK_MG 780
#define IMG_PK_SNIPER 781
#define IMG_PK_RPG 782
#define IMG_PK_AMMO 783
#define IMG_ROCKET 784
#define IMG_ROTOR0 785
#define IMG_ROTOR1 786
#define IMG_ROTOR2 787
#define IMG_ROTOR3 788
#define IMG_IC_FISTS 789
#define IMG_IC_PISTOL 790
#define IMG_IC_SMG 791
#define IMG_IC_SHOTGUN 792
#define IMG_IC_RIFLE 793
#define IMG_IC_MG 794
#define IMG_IC_SNIPER 795
#define IMG_IC_RPG 796

__attribute__((unused)) static const uint8_t tile_flags[NTILES] = {0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,64,16,16,16,16,16,16,16,16,16,16,16,16,16,0,0,16,16,16,16,16,1,16,16,16,16,1,0,0,16,16,16,0,9,9,9,9,8,9,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,0,0,0,0,0,0,0,0,35,35,35,35,35,35,3,3,3,3,3,3,3,3,3,35,35,35,35,35,35,35,35,35,35,35,35,35,35,35,35,0,0,0,5,5,5,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1};

#ifdef HOST_PREVIEW
__attribute__((unused)) static const char *const atlas_names[IMG_COUNT] = {
	"grass0",
	"grass1",
	"grass2",
	"dirt0",
	"dirt1",
	"scrub0",
	"scrub1",
	"sand0",
	"sand1",
	"wetsand",
	"sidewalk0",
	"sidewalk1",
	"plaza0",
	"plaza1",
	"star_walk",
	"wood0",
	"wood1",
	"concrete0",
	"concrete1",
	"court0",
	"spray_pad",
	"road",
	"road1",
	"road2",
	"road_hy_b",
	"road_hy_t",
	"road_hw_b",
	"road_hw_t",
	"road_vy_r",
	"road_vy_l",
	"road_vw_r",
	"road_vw_l",
	"cw_v",
	"cw_h",
	"parking_v",
	"parking_h",
	"fw",
	"fw_dash_l",
	"fw_dash_r",
	"fw_edge_l",
	"fw_edge_r",
	"fw_barrier",
	"fw_edge_t",
	"fw_edge_b",
	"fw_dash_t",
	"fw_dash_b",
	"fw_barrier_h",
	"rail_h",
	"rail_v",
	"rail_x_v",
	"rail_x_h",
	"runway",
	"runway_dash",
	"ocean0",
	"ocean1",
	"water0",
	"water1",
	"stream",
	"pool0",
	"roof_gray0",
	"roof_gray1",
	"roof_gray2",
	"roof_gray3",
	"roof_tan0",
	"roof_tan1",
	"roof_tan2",
	"roof_tan3",
	"roof_brown0",
	"roof_brown1",
	"roof_brown2",
	"roof_brown3",
	"roof_red0",
	"roof_red1",
	"roof_red2",
	"roof_red3",
	"roof_blue0",
	"roof_blue1",
	"roof_blue2",
	"roof_blue3",
	"roof_teal0",
	"roof_teal1",
	"roof_teal2",
	"roof_teal3",
	"roof_white0",
	"roof_white1",
	"roof_white2",
	"roof_white3",
	"roof_dark0",
	"roof_dark1",
	"roof_dark2",
	"roof_dark3",
	"roof_green0",
	"roof_green1",
	"roof_green2",
	"roof_green3",
	"roof_orange0",
	"roof_orange1",
	"roof_orange2",
	"roof_orange3",
	"roof_theatre",
	"roof_garage",
	"roof_police",
	"roof_station",
	"stand",
	"hosp_0",
	"hosp_1",
	"hosp_2",
	"hosp_3",
	"hosp_4",
	"hosp_5",
	"hosp_6",
	"hosp_7",
	"hosp_8",
	"pad_0",
	"pad_1",
	"pad_2",
	"pad_3",
	"pad_4",
	"pad_5",
	"pad_6",
	"pad_7",
	"pad_8",
	"tower_glass0",
	"tower_glass1",
	"tower_dark0",
	"tower_dark1",
	"tower_stone0",
	"tower_stone1",
	"obs_0",
	"obs_1",
	"obs_2",
	"obs_3",
	"obs_4",
	"obs_5",
	"obs_6",
	"obs_7",
	"obs_8",
	"ferris_0",
	"ferris_1",
	"ferris_2",
	"ferris_3",
	"ferris_4",
	"ferris_5",
	"ferris_6",
	"ferris_7",
	"ferris_8",
	"ferris_9",
	"ferris_10",
	"ferris_11",
	"ferris_12",
	"ferris_13",
	"ferris_14",
	"ferris_15",
	"field0",
	"field1",
	"track",
	"tree0",
	"tree1",
	"palm",
	"bush",
	"hsign_0_0",
	"hsign_0_1",
	"hsign_0_2",
	"hsign_0_3",
	"hsign_0_4",
	"hsign_0_5",
	"hsign_0_6",
	"hsign_0_7",
	"hsign_0_8",
	"hsign_0_9",
	"hsign_0_10",
	"hsign_0_11",
	"hsign_0_12",
	"hsign_0_13",
	"hsign_0_14",
	"hsign_0_15",
	"hsign_0_16",
	"hsign_0_17",
	"hsign_1_0",
	"hsign_1_1",
	"hsign_1_2",
	"hsign_1_3",
	"hsign_1_4",
	"hsign_1_5",
	"hsign_1_6",
	"hsign_1_7",
	"hsign_1_8",
	"hsign_1_9",
	"hsign_1_10",
	"hsign_1_11",
	"hsign_1_12",
	"hsign_1_13",
	"hsign_1_14",
	"hsign_1_15",
	"hsign_1_16",
	"hsign_1_17",
	"hsign_2_0",
	"hsign_2_1",
	"hsign_2_2",
	"hsign_2_3",
	"hsign_2_4",
	"hsign_2_5",
	"hsign_2_6",
	"hsign_2_7",
	"hsign_2_8",
	"hsign_2_9",
	"hsign_2_10",
	"hsign_2_11",
	"hsign_2_12",
	"hsign_2_13",
	"hsign_2_14",
	"hsign_2_15",
	"hsign_2_16",
	"hsign_2_17",
	"edge_n",
	"edge_e",
	"edge_s",
	"edge_w",
	"canopy0",
	"canopy1",
	"palmtop",
	"shadow",
	"gun_1_0",
	"gun_1_1",
	"gun_1_2",
	"gun_1_3",
	"gun_1_4",
	"gun_1_5",
	"gun_1_6",
	"gun_1_7",
	"gun_1_8",
	"gun_1_9",
	"gun_1_10",
	"gun_1_11",
	"gun_1_12",
	"gun_1_13",
	"gun_1_14",
	"gun_1_15",
	"gun_2_0",
	"gun_2_1",
	"gun_2_2",
	"gun_2_3",
	"gun_2_4",
	"gun_2_5",
	"gun_2_6",
	"gun_2_7",
	"gun_2_8",
	"gun_2_9",
	"gun_2_10",
	"gun_2_11",
	"gun_2_12",
	"gun_2_13",
	"gun_2_14",
	"gun_2_15",
	"gun_3_0",
	"gun_3_1",
	"gun_3_2",
	"gun_3_3",
	"gun_3_4",
	"gun_3_5",
	"gun_3_6",
	"gun_3_7",
	"gun_3_8",
	"gun_3_9",
	"gun_3_10",
	"gun_3_11",
	"gun_3_12",
	"gun_3_13",
	"gun_3_14",
	"gun_3_15",
	"gun_4_0",
	"gun_4_1",
	"gun_4_2",
	"gun_4_3",
	"gun_4_4",
	"gun_4_5",
	"gun_4_6",
	"gun_4_7",
	"gun_4_8",
	"gun_4_9",
	"gun_4_10",
	"gun_4_11",
	"gun_4_12",
	"gun_4_13",
	"gun_4_14",
	"gun_4_15",
	"gun_5_0",
	"gun_5_1",
	"gun_5_2",
	"gun_5_3",
	"gun_5_4",
	"gun_5_5",
	"gun_5_6",
	"gun_5_7",
	"gun_5_8",
	"gun_5_9",
	"gun_5_10",
	"gun_5_11",
	"gun_5_12",
	"gun_5_13",
	"gun_5_14",
	"gun_5_15",
	"gun_6_0",
	"gun_6_1",
	"gun_6_2",
	"gun_6_3",
	"gun_6_4",
	"gun_6_5",
	"gun_6_6",
	"gun_6_7",
	"gun_6_8",
	"gun_6_9",
	"gun_6_10",
	"gun_6_11",
	"gun_6_12",
	"gun_6_13",
	"gun_6_14",
	"gun_6_15",
	"gun_7_0",
	"gun_7_1",
	"gun_7_2",
	"gun_7_3",
	"gun_7_4",
	"gun_7_5",
	"gun_7_6",
	"gun_7_7",
	"gun_7_8",
	"gun_7_9",
	"gun_7_10",
	"gun_7_11",
	"gun_7_12",
	"gun_7_13",
	"gun_7_14",
	"gun_7_15",
	"player_0_0",
	"player_0_1",
	"player_0_2",
	"player_0_3",
	"player_0_4",
	"player_0_5",
	"player_0_6",
	"player_0_7",
	"player_0_8",
	"player_0_9",
	"player_0_10",
	"player_0_11",
	"player_0_12",
	"player_0_13",
	"player_0_14",
	"player_0_15",
	"player_1_0",
	"player_1_1",
	"player_1_2",
	"player_1_3",
	"player_1_4",
	"player_1_5",
	"player_1_6",
	"player_1_7",
	"player_1_8",
	"player_1_9",
	"player_1_10",
	"player_1_11",
	"player_1_12",
	"player_1_13",
	"player_1_14",
	"player_1_15",
	"player_2_0",
	"player_2_1",
	"player_2_2",
	"player_2_3",
	"player_2_4",
	"player_2_5",
	"player_2_6",
	"player_2_7",
	"player_2_8",
	"player_2_9",
	"player_2_10",
	"player_2_11",
	"player_2_12",
	"player_2_13",
	"player_2_14",
	"player_2_15",
	"player_3_0",
	"player_3_1",
	"player_3_2",
	"player_3_3",
	"player_3_4",
	"player_3_5",
	"player_3_6",
	"player_3_7",
	"player_3_8",
	"player_3_9",
	"player_3_10",
	"player_3_11",
	"player_3_12",
	"player_3_13",
	"player_3_14",
	"player_3_15",
	"car_0_0",
	"car_0_1",
	"car_0_2",
	"car_0_3",
	"car_0_4",
	"car_0_5",
	"car_0_6",
	"car_0_7",
	"car_0_8",
	"car_0_9",
	"car_0_10",
	"car_0_11",
	"car_0_12",
	"car_0_13",
	"car_0_14",
	"car_0_15",
	"car_1_0",
	"car_1_1",
	"car_1_2",
	"car_1_3",
	"car_1_4",
	"car_1_5",
	"car_1_6",
	"car_1_7",
	"car_1_8",
	"car_1_9",
	"car_1_10",
	"car_1_11",
	"car_1_12",
	"car_1_13",
	"car_1_14",
	"car_1_15",
	"car_2_0",
	"car_2_1",
	"car_2_2",
	"car_2_3",
	"car_2_4",
	"car_2_5",
	"car_2_6",
	"car_2_7",
	"car_2_8",
	"car_2_9",
	"car_2_10",
	"car_2_11",
	"car_2_12",
	"car_2_13",
	"car_2_14",
	"car_2_15",
	"car_3_0",
	"car_3_1",
	"car_3_2",
	"car_3_3",
	"car_3_4",
	"car_3_5",
	"car_3_6",
	"car_3_7",
	"car_3_8",
	"car_3_9",
	"car_3_10",
	"car_3_11",
	"car_3_12",
	"car_3_13",
	"car_3_14",
	"car_3_15",
	"car_4_0",
	"car_4_1",
	"car_4_2",
	"car_4_3",
	"car_4_4",
	"car_4_5",
	"car_4_6",
	"car_4_7",
	"car_4_8",
	"car_4_9",
	"car_4_10",
	"car_4_11",
	"car_4_12",
	"car_4_13",
	"car_4_14",
	"car_4_15",
	"car_5_0",
	"car_5_1",
	"car_5_2",
	"car_5_3",
	"car_5_4",
	"car_5_5",
	"car_5_6",
	"car_5_7",
	"car_5_8",
	"car_5_9",
	"car_5_10",
	"car_5_11",
	"car_5_12",
	"car_5_13",
	"car_5_14",
	"car_5_15",
	"car_6_0",
	"car_6_1",
	"car_6_2",
	"car_6_3",
	"car_6_4",
	"car_6_5",
	"car_6_6",
	"car_6_7",
	"car_6_8",
	"car_6_9",
	"car_6_10",
	"car_6_11",
	"car_6_12",
	"car_6_13",
	"car_6_14",
	"car_6_15",
	"car_7_0",
	"car_7_1",
	"car_7_2",
	"car_7_3",
	"car_7_4",
	"car_7_5",
	"car_7_6",
	"car_7_7",
	"car_7_8",
	"car_7_9",
	"car_7_10",
	"car_7_11",
	"car_7_12",
	"car_7_13",
	"car_7_14",
	"car_7_15",
	"car_8_0",
	"car_8_1",
	"car_8_2",
	"car_8_3",
	"car_8_4",
	"car_8_5",
	"car_8_6",
	"car_8_7",
	"car_8_8",
	"car_8_9",
	"car_8_10",
	"car_8_11",
	"car_8_12",
	"car_8_13",
	"car_8_14",
	"car_8_15",
	"car_9_0",
	"car_9_1",
	"car_9_2",
	"car_9_3",
	"car_9_4",
	"car_9_5",
	"car_9_6",
	"car_9_7",
	"car_9_8",
	"car_9_9",
	"car_9_10",
	"car_9_11",
	"car_9_12",
	"car_9_13",
	"car_9_14",
	"car_9_15",
	"car_10_0",
	"car_10_1",
	"car_10_2",
	"car_10_3",
	"car_10_4",
	"car_10_5",
	"car_10_6",
	"car_10_7",
	"car_10_8",
	"car_10_9",
	"car_10_10",
	"car_10_11",
	"car_10_12",
	"car_10_13",
	"car_10_14",
	"car_10_15",
	"car_11_0",
	"car_11_1",
	"car_11_2",
	"car_11_3",
	"car_11_4",
	"car_11_5",
	"car_11_6",
	"car_11_7",
	"car_11_8",
	"car_11_9",
	"car_11_10",
	"car_11_11",
	"car_11_12",
	"car_11_13",
	"car_11_14",
	"car_11_15",
	"ped_0_0_0",
	"ped_0_0_1",
	"ped_0_0_2",
	"ped_0_0_3",
	"ped_0_0_4",
	"ped_0_0_5",
	"ped_0_0_6",
	"ped_0_0_7",
	"ped_0_1_0",
	"ped_0_1_1",
	"ped_0_1_2",
	"ped_0_1_3",
	"ped_0_1_4",
	"ped_0_1_5",
	"ped_0_1_6",
	"ped_0_1_7",
	"ped_1_0_0",
	"ped_1_0_1",
	"ped_1_0_2",
	"ped_1_0_3",
	"ped_1_0_4",
	"ped_1_0_5",
	"ped_1_0_6",
	"ped_1_0_7",
	"ped_1_1_0",
	"ped_1_1_1",
	"ped_1_1_2",
	"ped_1_1_3",
	"ped_1_1_4",
	"ped_1_1_5",
	"ped_1_1_6",
	"ped_1_1_7",
	"ped_2_0_0",
	"ped_2_0_1",
	"ped_2_0_2",
	"ped_2_0_3",
	"ped_2_0_4",
	"ped_2_0_5",
	"ped_2_0_6",
	"ped_2_0_7",
	"ped_2_1_0",
	"ped_2_1_1",
	"ped_2_1_2",
	"ped_2_1_3",
	"ped_2_1_4",
	"ped_2_1_5",
	"ped_2_1_6",
	"ped_2_1_7",
	"ped_3_0_0",
	"ped_3_0_1",
	"ped_3_0_2",
	"ped_3_0_3",
	"ped_3_0_4",
	"ped_3_0_5",
	"ped_3_0_6",
	"ped_3_0_7",
	"ped_3_1_0",
	"ped_3_1_1",
	"ped_3_1_2",
	"ped_3_1_3",
	"ped_3_1_4",
	"ped_3_1_5",
	"ped_3_1_6",
	"ped_3_1_7",
	"ped_4_0_0",
	"ped_4_0_1",
	"ped_4_0_2",
	"ped_4_0_3",
	"ped_4_0_4",
	"ped_4_0_5",
	"ped_4_0_6",
	"ped_4_0_7",
	"ped_4_1_0",
	"ped_4_1_1",
	"ped_4_1_2",
	"ped_4_1_3",
	"ped_4_1_4",
	"ped_4_1_5",
	"ped_4_1_6",
	"ped_4_1_7",
	"ped_5_0_0",
	"ped_5_0_1",
	"ped_5_0_2",
	"ped_5_0_3",
	"ped_5_0_4",
	"ped_5_0_5",
	"ped_5_0_6",
	"ped_5_0_7",
	"ped_5_1_0",
	"ped_5_1_1",
	"ped_5_1_2",
	"ped_5_1_3",
	"ped_5_1_4",
	"ped_5_1_5",
	"ped_5_1_6",
	"ped_5_1_7",
	"ped_6_0_0",
	"ped_6_0_1",
	"ped_6_0_2",
	"ped_6_0_3",
	"ped_6_0_4",
	"ped_6_0_5",
	"ped_6_0_6",
	"ped_6_0_7",
	"ped_6_1_0",
	"ped_6_1_1",
	"ped_6_1_2",
	"ped_6_1_3",
	"ped_6_1_4",
	"ped_6_1_5",
	"ped_6_1_6",
	"ped_6_1_7",
	"ped_7_0_0",
	"ped_7_0_1",
	"ped_7_0_2",
	"ped_7_0_3",
	"ped_7_0_4",
	"ped_7_0_5",
	"ped_7_0_6",
	"ped_7_0_7",
	"ped_7_1_0",
	"ped_7_1_1",
	"ped_7_1_2",
	"ped_7_1_3",
	"ped_7_1_4",
	"ped_7_1_5",
	"ped_7_1_6",
	"ped_7_1_7",
	"corpse_0_0",
	"corpse_0_1",
	"corpse_0_2",
	"corpse_0_3",
	"corpse_1_0",
	"corpse_1_1",
	"corpse_1_2",
	"corpse_1_3",
	"corpse_2_0",
	"corpse_2_1",
	"corpse_2_2",
	"corpse_2_3",
	"corpse_3_0",
	"corpse_3_1",
	"corpse_3_2",
	"corpse_3_3",
	"corpse_4_0",
	"corpse_4_1",
	"corpse_4_2",
	"corpse_4_3",
	"corpse_5_0",
	"corpse_5_1",
	"corpse_5_2",
	"corpse_5_3",
	"corpse_6_0",
	"corpse_6_1",
	"corpse_6_2",
	"corpse_6_3",
	"corpse_7_0",
	"corpse_7_1",
	"corpse_7_2",
	"corpse_7_3",
	"muzzle",
	"bullet",
	"spark",
	"blood_dot",
	"glow_red",
	"glow_blue",
	"shadow_car",
	"stain0",
	"stain1",
	"stain2",
	"stain3",
	"boom0",
	"boom1",
	"boom2",
	"boom3",
	"boom4",
	"boom5",
	"smoke0",
	"smoke1",
	"smoke2",
	"fire0",
	"fire1",
	"fire2",
	"pk_health",
	"pk_armor",
	"pk_pistol",
	"pk_smg",
	"pk_shotgun",
	"pk_cash",
	"pk_rifle",
	"pk_mg",
	"pk_sniper",
	"pk_rpg",
	"pk_ammo",
	"rocket",
	"rotor0",
	"rotor1",
	"rotor2",
	"rotor3",
	"ic_fists",
	"ic_pistol",
	"ic_smg",
	"ic_shotgun",
	"ic_rifle",
	"ic_mg",
	"ic_sniper",
	"ic_rpg",
	"minimap",
};
#endif
