// GENERATED by assets/make_map.py - do not edit
#pragma once

#define MAP_W 160
#define MAP_H 160

typedef struct { const char *name; int x0, y0, x1, y1; } Zone;
__attribute__((unused)) static const Zone zones[] = {
	{"Los Angeles", 0, 0, 159, 159},
	{"Pacific Ocean", 0, 0, 15, 159},
	{"Malibu", 10, 0, 40, 19},
	{"Hollywood Hills", 28, 0, 137, 19},
	{"Griffith Park", 104, 0, 137, 19},
	{"Santa Monica", 16, 28, 35, 70},
	{"Venice Beach", 16, 71, 35, 117},
	{"Beverly Hills", 36, 28, 68, 57},
	{"Rodeo Drive", 36, 66, 68, 77},
	{"West Hollywood", 69, 28, 95, 47},
	{"Silver Lake", 84, 48, 95, 57},
	{"Hollywood", 69, 48, 115, 77},
	{"Elysian Park", 104, 28, 123, 57},
	{"Dodger Stadium", 124, 28, 137, 57},
	{"Downtown LA", 84, 87, 123, 117},
	{"Union Station", 124, 87, 137, 117},
	{"Venice Canals", 36, 104, 59, 117},
	{"Mid-City", 69, 87, 83, 117},
	{"Koreatown", 69, 127, 95, 139},
	{"Inglewood", 24, 127, 59, 139},
	{"Exposition Park", 96, 127, 137, 139},
	{"LAX", 22, 148, 137, 159},
	{"LA River", 138, 0, 146, 159},
	{"Freeway 405", 60, 0, 68, 159},
	{"Freeway 5", 147, 0, 155, 159},
	{"Industrial", 156, 0, 159, 159},
};
#define NZONES (int)(sizeof zones / sizeof zones[0])

typedef struct { const char *name; int tx, ty; } Landmark;
__attribute__((unused)) static const Landmark landmarks[] = {
	{"Santa Monica Pier", 20, 60},
	{"Pacific Park", 8, 59},
	{"Venice Boardwalk", 22, 74},
	{"Muscle Beach", 21, 86},
	{"Venice Canals", 48, 103},
	{"Rodeo Drive", 48, 66},
	{"Hollywood Sign", 95, 2},
	{"Griffith Observatory", 121, 8},
	{"Chinese Theatre", 90, 66},
	{"Walk of Fame", 100, 55},
	{"Capitol Records", 111, 66},
	{"Silver Lake", 90, 48},
	{"Dodger Stadium", 130, 28},
	{"City Hall", 110, 87},
	{"Union Station", 130, 86},
	{"LA River", 141, 40},
	{"LA Coliseum", 110, 127},
	{"LAX", 94, 147},
	{"Theme Building", 73, 147},
	{"Sunset Blvd", 60, 38},
};
#define NLANDMARKS (int)(sizeof landmarks / sizeof landmarks[0])

// streets: a0..a1 = tiles across the street, b0..b1 = tiles along it. hroads run along x, vroads along y.
typedef struct { int a0, a1, b0, b1; } RoadDef;
__attribute__((unused)) static const RoadDef hroads[] = {
	{20, 27, 24, 159},
	{40, 47, 24, 137},
	{58, 65, 24, 159},
	{96, 103, 24, 159},
	{140, 147, 24, 137},
};
__attribute__((unused)) static const RoadDef vroads[] = {
	{28, 35, 20, 147},
	{76, 83, 0, 147},
	{96, 103, 20, 147},
	{116, 123, 20, 147},
};
#define NHROADS (int)(sizeof hroads / sizeof hroads[0])
#define NVROADS (int)(sizeof vroads / sizeof vroads[0])

#define HOSPITAL_X 89
#define HOSPITAL_Y 137
#define POLICE_X 43
#define POLICE_Y 95

typedef struct { int x0, y0, x1, y1; } SprayPad;
__attribute__((unused)) static const SprayPad spray_pads[] = {
	{105, 67, 109, 69},
	{42, 135, 48, 137},
};
#define NSPRAY (int)(sizeof spray_pads / sizeof spray_pads[0])

typedef struct { int tx, ty, kind; } PickupSpot;      // kind: 0 health, 1 armor, 2 pistol, 3 smg, 4 shotgun, 5 cash
__attribute__((unused)) static const PickupSpot pickup_spots[] = {
	{94, 49, 0},
	{124, 105, 0},
	{146, 67, 0},
	{50, 116, 0},
	{87, 95, 0},
	{103, 17, 0},
	{132, 4, 0},
	{52, 138, 0},
	{36, 133, 0},
	{50, 54, 0},
	{58, 37, 1},
	{137, 105, 1},
	{49, 30, 1},
	{85, 69, 1},
	{39, 80, 1},
	{71, 66, 1},
	{57, 6, 1},
	{115, 128, 1},
	{85, 57, 2},
	{59, 83, 2},
	{137, 132, 2},
	{135, 113, 2},
	{93, 113, 2},
	{27, 66, 2},
	{111, 37, 3},
	{30, 7, 3},
	{95, 152, 3},
	{27, 116, 3},
	{112, 110, 3},
	{136, 72, 3},
	{131, 128, 4},
	{146, 53, 4},
	{132, 19, 4},
	{104, 130, 4},
	{38, 28, 4},
	{92, 32, 5},
	{55, 66, 5},
	{129, 87, 5},
	{24, 151, 5},
	{24, 4, 5},
	{108, 138, 5},
	{104, 77, 5},
	{125, 149, 5},
	{146, 2, 5},
	{25, 55, 5},
	{86, 2, 5},
	{118, 12, 5},
	{146, 146, 5},
	{39, 38, 5},
	{46, 85, 5},
	{53, 87, 5},
};
#define NPICKUPS (int)(sizeof pickup_spots / sizeof pickup_spots[0])

typedef struct { int tx, ty, dir; } ParkSpot;         // dir: heading in 1/16 turns clockwise from up
__attribute__((unused)) static const ParkSpot park_spots[] = {
	{126, 48, 0},
	{128, 48, 0},
	{130, 48, 0},
	{132, 48, 8},
	{134, 48, 8},
	{136, 48, 0},
	{126, 51, 0},
	{128, 51, 0},
	{130, 51, 8},
	{132, 51, 0},
	{134, 51, 0},
	{136, 51, 0},
	{126, 54, 8},
	{128, 54, 0},
	{130, 54, 0},
	{132, 54, 8},
	{134, 54, 0},
	{136, 54, 8},
	{50, 90, 8},
	{52, 90, 8},
	{54, 90, 0},
	{56, 90, 8},
	{126, 105, 8},
	{128, 105, 0},
	{130, 105, 8},
	{126, 108, 8},
	{128, 108, 8},
	{130, 108, 0},
	{126, 111, 8},
	{128, 111, 0},
	{130, 111, 8},
	{126, 114, 8},
	{128, 114, 8},
	{130, 114, 8},
	{84, 128, 4},
	{87, 128, 12},
	{90, 128, 12},
	{93, 128, 4},
	{84, 136, 12},
	{87, 136, 4},
	{90, 136, 12},
	{93, 136, 12},
	{84, 138, 12},
	{87, 138, 12},
	{90, 138, 4},
	{93, 138, 4},
	{32, 150, 0},
	{34, 150, 0},
	{36, 150, 0},
	{38, 150, 0},
	{54, 150, 0},
	{80, 150, 0},
	{82, 150, 0},
	{98, 150, 0},
	{100, 150, 8},
	{102, 150, 0},
	{118, 150, 8},
	{128, 150, 8},
	{130, 150, 8},
	{132, 150, 0},
	{134, 150, 0},
};
#define NPARK (int)(sizeof park_spots / sizeof park_spots[0])
