// GENERATED by assets/make_art.py - do not edit
#pragma once
#include <stdint.h>

#define NTILES 203
#define IMG_COUNT 645
#define F_SOLID 1
#define F_BUILDING 2
#define F_TREE 4
#define F_WATER 8
#define F_ROAD 16
#define F_TALL 32
#define F_SPRAY 64

#define TILE_GRASS0 0
#define TILE_GRASS1 1
#define TILE_GRASS2 2
#define TILE_DIRT0 3
#define TILE_DIRT1 4
#define TILE_SCRUB0 5
#define TILE_SCRUB1 6
#define TILE_SAND0 7
#define TILE_SAND1 8
#define TILE_WETSAND 9
#define TILE_SIDEWALK0 10
#define TILE_SIDEWALK1 11
#define TILE_PLAZA0 12
#define TILE_PLAZA1 13
#define TILE_STAR_WALK 14
#define TILE_WOOD0 15
#define TILE_WOOD1 16
#define TILE_CONCRETE0 17
#define TILE_CONCRETE1 18
#define TILE_COURT0 19
#define TILE_SPRAY_PAD 20
#define TILE_ROAD 21
#define TILE_ROAD_HY_B 22
#define TILE_ROAD_HY_T 23
#define TILE_ROAD_HW_B 24
#define TILE_ROAD_HW_T 25
#define TILE_ROAD_VY_R 26
#define TILE_ROAD_VY_L 27
#define TILE_ROAD_VW_R 28
#define TILE_ROAD_VW_L 29
#define TILE_CW_V 30
#define TILE_CW_H 31
#define TILE_PARKING_V 32
#define TILE_PARKING_H 33
#define TILE_FW 34
#define TILE_FW_DASH_L 35
#define TILE_FW_DASH_R 36
#define TILE_FW_EDGE_L 37
#define TILE_FW_EDGE_R 38
#define TILE_FW_BARRIER 39
#define TILE_FW_EDGE_T 40
#define TILE_FW_EDGE_B 41
#define TILE_FW_DASH_T 42
#define TILE_FW_DASH_B 43
#define TILE_FW_BARRIER_H 44
#define TILE_RAIL_H 45
#define TILE_RAIL_V 46
#define TILE_RAIL_X_V 47
#define TILE_RAIL_X_H 48
#define TILE_RUNWAY 49
#define TILE_RUNWAY_DASH 50
#define TILE_OCEAN0 51
#define TILE_OCEAN1 52
#define TILE_WATER0 53
#define TILE_WATER1 54
#define TILE_STREAM 55
#define TILE_POOL0 56
#define TILE_ROOF_GRAY0 57
#define TILE_ROOF_GRAY1 58
#define TILE_ROOF_GRAY2 59
#define TILE_ROOF_GRAY3 60
#define TILE_ROOF_TAN0 61
#define TILE_ROOF_TAN1 62
#define TILE_ROOF_TAN2 63
#define TILE_ROOF_TAN3 64
#define TILE_ROOF_BROWN0 65
#define TILE_ROOF_BROWN1 66
#define TILE_ROOF_BROWN2 67
#define TILE_ROOF_BROWN3 68
#define TILE_ROOF_RED0 69
#define TILE_ROOF_RED1 70
#define TILE_ROOF_RED2 71
#define TILE_ROOF_RED3 72
#define TILE_ROOF_BLUE0 73
#define TILE_ROOF_BLUE1 74
#define TILE_ROOF_BLUE2 75
#define TILE_ROOF_BLUE3 76
#define TILE_ROOF_TEAL0 77
#define TILE_ROOF_TEAL1 78
#define TILE_ROOF_TEAL2 79
#define TILE_ROOF_TEAL3 80
#define TILE_ROOF_WHITE0 81
#define TILE_ROOF_WHITE1 82
#define TILE_ROOF_WHITE2 83
#define TILE_ROOF_WHITE3 84
#define TILE_ROOF_DARK0 85
#define TILE_ROOF_DARK1 86
#define TILE_ROOF_DARK2 87
#define TILE_ROOF_DARK3 88
#define TILE_ROOF_GREEN0 89
#define TILE_ROOF_GREEN1 90
#define TILE_ROOF_GREEN2 91
#define TILE_ROOF_GREEN3 92
#define TILE_ROOF_ORANGE0 93
#define TILE_ROOF_ORANGE1 94
#define TILE_ROOF_ORANGE2 95
#define TILE_ROOF_ORANGE3 96
#define TILE_ROOF_THEATRE 97
#define TILE_ROOF_GARAGE 98
#define TILE_ROOF_POLICE 99
#define TILE_ROOF_STATION 100
#define TILE_STAND 101
#define TILE_HOSP_0 102
#define TILE_HOSP_1 103
#define TILE_HOSP_2 104
#define TILE_HOSP_3 105
#define TILE_HOSP_4 106
#define TILE_HOSP_5 107
#define TILE_HOSP_6 108
#define TILE_HOSP_7 109
#define TILE_HOSP_8 110
#define TILE_TOWER_GLASS0 111
#define TILE_TOWER_GLASS1 112
#define TILE_TOWER_DARK0 113
#define TILE_TOWER_DARK1 114
#define TILE_TOWER_STONE0 115
#define TILE_TOWER_STONE1 116
#define TILE_OBS_0 117
#define TILE_OBS_1 118
#define TILE_OBS_2 119
#define TILE_OBS_3 120
#define TILE_OBS_4 121
#define TILE_OBS_5 122
#define TILE_OBS_6 123
#define TILE_OBS_7 124
#define TILE_OBS_8 125
#define TILE_FERRIS_0 126
#define TILE_FERRIS_1 127
#define TILE_FERRIS_2 128
#define TILE_FERRIS_3 129
#define TILE_FERRIS_4 130
#define TILE_FERRIS_5 131
#define TILE_FERRIS_6 132
#define TILE_FERRIS_7 133
#define TILE_FERRIS_8 134
#define TILE_FERRIS_9 135
#define TILE_FERRIS_10 136
#define TILE_FERRIS_11 137
#define TILE_FERRIS_12 138
#define TILE_FERRIS_13 139
#define TILE_FERRIS_14 140
#define TILE_FERRIS_15 141
#define TILE_FIELD0 142
#define TILE_FIELD1 143
#define TILE_TRACK 144
#define TILE_TREE0 145
#define TILE_TREE1 146
#define TILE_PALM 147
#define TILE_BUSH 148
#define TILE_HSIGN_0_0 149
#define TILE_HSIGN_0_1 150
#define TILE_HSIGN_0_2 151
#define TILE_HSIGN_0_3 152
#define TILE_HSIGN_0_4 153
#define TILE_HSIGN_0_5 154
#define TILE_HSIGN_0_6 155
#define TILE_HSIGN_0_7 156
#define TILE_HSIGN_0_8 157
#define TILE_HSIGN_0_9 158
#define TILE_HSIGN_0_10 159
#define TILE_HSIGN_0_11 160
#define TILE_HSIGN_0_12 161
#define TILE_HSIGN_0_13 162
#define TILE_HSIGN_0_14 163
#define TILE_HSIGN_0_15 164
#define TILE_HSIGN_0_16 165
#define TILE_HSIGN_0_17 166
#define TILE_HSIGN_1_0 167
#define TILE_HSIGN_1_1 168
#define TILE_HSIGN_1_2 169
#define TILE_HSIGN_1_3 170
#define TILE_HSIGN_1_4 171
#define TILE_HSIGN_1_5 172
#define TILE_HSIGN_1_6 173
#define TILE_HSIGN_1_7 174
#define TILE_HSIGN_1_8 175
#define TILE_HSIGN_1_9 176
#define TILE_HSIGN_1_10 177
#define TILE_HSIGN_1_11 178
#define TILE_HSIGN_1_12 179
#define TILE_HSIGN_1_13 180
#define TILE_HSIGN_1_14 181
#define TILE_HSIGN_1_15 182
#define TILE_HSIGN_1_16 183
#define TILE_HSIGN_1_17 184
#define TILE_HSIGN_2_0 185
#define TILE_HSIGN_2_1 186
#define TILE_HSIGN_2_2 187
#define TILE_HSIGN_2_3 188
#define TILE_HSIGN_2_4 189
#define TILE_HSIGN_2_5 190
#define TILE_HSIGN_2_6 191
#define TILE_HSIGN_2_7 192
#define TILE_HSIGN_2_8 193
#define TILE_HSIGN_2_9 194
#define TILE_HSIGN_2_10 195
#define TILE_HSIGN_2_11 196
#define TILE_HSIGN_2_12 197
#define TILE_HSIGN_2_13 198
#define TILE_HSIGN_2_14 199
#define TILE_HSIGN_2_15 200
#define TILE_HSIGN_2_16 201
#define TILE_HSIGN_2_17 202

#define IMG_EDGE_N 203
#define IMG_EDGE_E 204
#define IMG_EDGE_S 205
#define IMG_EDGE_W 206
#define IMG_CANOPY0 207
#define IMG_CANOPY1 208
#define IMG_PALMTOP 209
#define IMG_SHADOW 210
#define IMG_MINIMAP 644
#define IMG_PLAYER_BASE 211
#define IMG_PLAYER(frame, dir) (IMG_PLAYER_BASE + (frame) * 16 + (dir))
#define DIRS 16
#define WALK_FRAMES 4
#define PED_DIRS 8
#define PED_FRAMES 2

#define NCARVARS 11
#define IMG_CAR_BASE 275
#define IMG_CAR(var, dir) (IMG_CAR_BASE + (var) * 16 + (dir))
__attribute__((unused)) static const uint8_t carvar_model[NCARVARS] = {0,0,1,1,1,2,2,3,4,5,6};
#define NPEDTYPES 8
#define IMG_PED_BASE 451
#define IMG_PED(t, f, dir) (IMG_PED_BASE + ((t) * 2 + (f)) * 8 + (dir))
#define IMG_CORPSE_BASE 579
#define IMG_CORPSE(t, k) (IMG_CORPSE_BASE + (t) * 4 + (k))
#define IMG_MUZZLE 611
#define IMG_BULLET 612
#define IMG_SPARK 613
#define IMG_BLOOD_DOT 614
#define IMG_GLOW_RED 615
#define IMG_GLOW_BLUE 616
#define IMG_SHADOW_CAR 617
#define IMG_STAIN0 618
#define IMG_STAIN1 619
#define IMG_STAIN2 620
#define IMG_STAIN3 621
#define IMG_BOOM0 622
#define IMG_BOOM1 623
#define IMG_BOOM2 624
#define IMG_BOOM3 625
#define IMG_BOOM4 626
#define IMG_BOOM5 627
#define IMG_SMOKE0 628
#define IMG_SMOKE1 629
#define IMG_SMOKE2 630
#define IMG_FIRE0 631
#define IMG_FIRE1 632
#define IMG_FIRE2 633
#define IMG_PK_HEALTH 634
#define IMG_PK_ARMOR 635
#define IMG_PK_PISTOL 636
#define IMG_PK_SMG 637
#define IMG_PK_SHOTGUN 638
#define IMG_PK_CASH 639
#define IMG_IC_FISTS 640
#define IMG_IC_PISTOL 641
#define IMG_IC_SMG 642
#define IMG_IC_SHOTGUN 643

__attribute__((unused)) static const uint8_t tile_flags[NTILES] = {0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,64,16,16,16,16,16,16,16,16,16,16,16,0,0,16,16,16,16,16,1,16,16,16,16,1,0,0,16,16,16,0,9,9,9,9,8,9,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,35,35,35,35,35,35,3,3,3,3,3,3,3,3,3,35,35,35,35,35,35,35,35,35,35,35,35,35,35,35,35,0,0,0,5,5,5,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1};

#ifdef HOST_PREVIEW
__attribute__((unused)) static const char *const atlas_names[IMG_COUNT] = {
	"grass0",
	"grass1",
	"grass2",
	"dirt0",
	"dirt1",
	"scrub0",
	"scrub1",
	"sand0",
	"sand1",
	"wetsand",
	"sidewalk0",
	"sidewalk1",
	"plaza0",
	"plaza1",
	"star_walk",
	"wood0",
	"wood1",
	"concrete0",
	"concrete1",
	"court0",
	"spray_pad",
	"road",
	"road_hy_b",
	"road_hy_t",
	"road_hw_b",
	"road_hw_t",
	"road_vy_r",
	"road_vy_l",
	"road_vw_r",
	"road_vw_l",
	"cw_v",
	"cw_h",
	"parking_v",
	"parking_h",
	"fw",
	"fw_dash_l",
	"fw_dash_r",
	"fw_edge_l",
	"fw_edge_r",
	"fw_barrier",
	"fw_edge_t",
	"fw_edge_b",
	"fw_dash_t",
	"fw_dash_b",
	"fw_barrier_h",
	"rail_h",
	"rail_v",
	"rail_x_v",
	"rail_x_h",
	"runway",
	"runway_dash",
	"ocean0",
	"ocean1",
	"water0",
	"water1",
	"stream",
	"pool0",
	"roof_gray0",
	"roof_gray1",
	"roof_gray2",
	"roof_gray3",
	"roof_tan0",
	"roof_tan1",
	"roof_tan2",
	"roof_tan3",
	"roof_brown0",
	"roof_brown1",
	"roof_brown2",
	"roof_brown3",
	"roof_red0",
	"roof_red1",
	"roof_red2",
	"roof_red3",
	"roof_blue0",
	"roof_blue1",
	"roof_blue2",
	"roof_blue3",
	"roof_teal0",
	"roof_teal1",
	"roof_teal2",
	"roof_teal3",
	"roof_white0",
	"roof_white1",
	"roof_white2",
	"roof_white3",
	"roof_dark0",
	"roof_dark1",
	"roof_dark2",
	"roof_dark3",
	"roof_green0",
	"roof_green1",
	"roof_green2",
	"roof_green3",
	"roof_orange0",
	"roof_orange1",
	"roof_orange2",
	"roof_orange3",
	"roof_theatre",
	"roof_garage",
	"roof_police",
	"roof_station",
	"stand",
	"hosp_0",
	"hosp_1",
	"hosp_2",
	"hosp_3",
	"hosp_4",
	"hosp_5",
	"hosp_6",
	"hosp_7",
	"hosp_8",
	"tower_glass0",
	"tower_glass1",
	"tower_dark0",
	"tower_dark1",
	"tower_stone0",
	"tower_stone1",
	"obs_0",
	"obs_1",
	"obs_2",
	"obs_3",
	"obs_4",
	"obs_5",
	"obs_6",
	"obs_7",
	"obs_8",
	"ferris_0",
	"ferris_1",
	"ferris_2",
	"ferris_3",
	"ferris_4",
	"ferris_5",
	"ferris_6",
	"ferris_7",
	"ferris_8",
	"ferris_9",
	"ferris_10",
	"ferris_11",
	"ferris_12",
	"ferris_13",
	"ferris_14",
	"ferris_15",
	"field0",
	"field1",
	"track",
	"tree0",
	"tree1",
	"palm",
	"bush",
	"hsign_0_0",
	"hsign_0_1",
	"hsign_0_2",
	"hsign_0_3",
	"hsign_0_4",
	"hsign_0_5",
	"hsign_0_6",
	"hsign_0_7",
	"hsign_0_8",
	"hsign_0_9",
	"hsign_0_10",
	"hsign_0_11",
	"hsign_0_12",
	"hsign_0_13",
	"hsign_0_14",
	"hsign_0_15",
	"hsign_0_16",
	"hsign_0_17",
	"hsign_1_0",
	"hsign_1_1",
	"hsign_1_2",
	"hsign_1_3",
	"hsign_1_4",
	"hsign_1_5",
	"hsign_1_6",
	"hsign_1_7",
	"hsign_1_8",
	"hsign_1_9",
	"hsign_1_10",
	"hsign_1_11",
	"hsign_1_12",
	"hsign_1_13",
	"hsign_1_14",
	"hsign_1_15",
	"hsign_1_16",
	"hsign_1_17",
	"hsign_2_0",
	"hsign_2_1",
	"hsign_2_2",
	"hsign_2_3",
	"hsign_2_4",
	"hsign_2_5",
	"hsign_2_6",
	"hsign_2_7",
	"hsign_2_8",
	"hsign_2_9",
	"hsign_2_10",
	"hsign_2_11",
	"hsign_2_12",
	"hsign_2_13",
	"hsign_2_14",
	"hsign_2_15",
	"hsign_2_16",
	"hsign_2_17",
	"edge_n",
	"edge_e",
	"edge_s",
	"edge_w",
	"canopy0",
	"canopy1",
	"palmtop",
	"shadow",
	"player_0_0",
	"player_0_1",
	"player_0_2",
	"player_0_3",
	"player_0_4",
	"player_0_5",
	"player_0_6",
	"player_0_7",
	"player_0_8",
	"player_0_9",
	"player_0_10",
	"player_0_11",
	"player_0_12",
	"player_0_13",
	"player_0_14",
	"player_0_15",
	"player_1_0",
	"player_1_1",
	"player_1_2",
	"player_1_3",
	"player_1_4",
	"player_1_5",
	"player_1_6",
	"player_1_7",
	"player_1_8",
	"player_1_9",
	"player_1_10",
	"player_1_11",
	"player_1_12",
	"player_1_13",
	"player_1_14",
	"player_1_15",
	"player_2_0",
	"player_2_1",
	"player_2_2",
	"player_2_3",
	"player_2_4",
	"player_2_5",
	"player_2_6",
	"player_2_7",
	"player_2_8",
	"player_2_9",
	"player_2_10",
	"player_2_11",
	"player_2_12",
	"player_2_13",
	"player_2_14",
	"player_2_15",
	"player_3_0",
	"player_3_1",
	"player_3_2",
	"player_3_3",
	"player_3_4",
	"player_3_5",
	"player_3_6",
	"player_3_7",
	"player_3_8",
	"player_3_9",
	"player_3_10",
	"player_3_11",
	"player_3_12",
	"player_3_13",
	"player_3_14",
	"player_3_15",
	"car_0_0",
	"car_0_1",
	"car_0_2",
	"car_0_3",
	"car_0_4",
	"car_0_5",
	"car_0_6",
	"car_0_7",
	"car_0_8",
	"car_0_9",
	"car_0_10",
	"car_0_11",
	"car_0_12",
	"car_0_13",
	"car_0_14",
	"car_0_15",
	"car_1_0",
	"car_1_1",
	"car_1_2",
	"car_1_3",
	"car_1_4",
	"car_1_5",
	"car_1_6",
	"car_1_7",
	"car_1_8",
	"car_1_9",
	"car_1_10",
	"car_1_11",
	"car_1_12",
	"car_1_13",
	"car_1_14",
	"car_1_15",
	"car_2_0",
	"car_2_1",
	"car_2_2",
	"car_2_3",
	"car_2_4",
	"car_2_5",
	"car_2_6",
	"car_2_7",
	"car_2_8",
	"car_2_9",
	"car_2_10",
	"car_2_11",
	"car_2_12",
	"car_2_13",
	"car_2_14",
	"car_2_15",
	"car_3_0",
	"car_3_1",
	"car_3_2",
	"car_3_3",
	"car_3_4",
	"car_3_5",
	"car_3_6",
	"car_3_7",
	"car_3_8",
	"car_3_9",
	"car_3_10",
	"car_3_11",
	"car_3_12",
	"car_3_13",
	"car_3_14",
	"car_3_15",
	"car_4_0",
	"car_4_1",
	"car_4_2",
	"car_4_3",
	"car_4_4",
	"car_4_5",
	"car_4_6",
	"car_4_7",
	"car_4_8",
	"car_4_9",
	"car_4_10",
	"car_4_11",
	"car_4_12",
	"car_4_13",
	"car_4_14",
	"car_4_15",
	"car_5_0",
	"car_5_1",
	"car_5_2",
	"car_5_3",
	"car_5_4",
	"car_5_5",
	"car_5_6",
	"car_5_7",
	"car_5_8",
	"car_5_9",
	"car_5_10",
	"car_5_11",
	"car_5_12",
	"car_5_13",
	"car_5_14",
	"car_5_15",
	"car_6_0",
	"car_6_1",
	"car_6_2",
	"car_6_3",
	"car_6_4",
	"car_6_5",
	"car_6_6",
	"car_6_7",
	"car_6_8",
	"car_6_9",
	"car_6_10",
	"car_6_11",
	"car_6_12",
	"car_6_13",
	"car_6_14",
	"car_6_15",
	"car_7_0",
	"car_7_1",
	"car_7_2",
	"car_7_3",
	"car_7_4",
	"car_7_5",
	"car_7_6",
	"car_7_7",
	"car_7_8",
	"car_7_9",
	"car_7_10",
	"car_7_11",
	"car_7_12",
	"car_7_13",
	"car_7_14",
	"car_7_15",
	"car_8_0",
	"car_8_1",
	"car_8_2",
	"car_8_3",
	"car_8_4",
	"car_8_5",
	"car_8_6",
	"car_8_7",
	"car_8_8",
	"car_8_9",
	"car_8_10",
	"car_8_11",
	"car_8_12",
	"car_8_13",
	"car_8_14",
	"car_8_15",
	"car_9_0",
	"car_9_1",
	"car_9_2",
	"car_9_3",
	"car_9_4",
	"car_9_5",
	"car_9_6",
	"car_9_7",
	"car_9_8",
	"car_9_9",
	"car_9_10",
	"car_9_11",
	"car_9_12",
	"car_9_13",
	"car_9_14",
	"car_9_15",
	"car_10_0",
	"car_10_1",
	"car_10_2",
	"car_10_3",
	"car_10_4",
	"car_10_5",
	"car_10_6",
	"car_10_7",
	"car_10_8",
	"car_10_9",
	"car_10_10",
	"car_10_11",
	"car_10_12",
	"car_10_13",
	"car_10_14",
	"car_10_15",
	"ped_0_0_0",
	"ped_0_0_1",
	"ped_0_0_2",
	"ped_0_0_3",
	"ped_0_0_4",
	"ped_0_0_5",
	"ped_0_0_6",
	"ped_0_0_7",
	"ped_0_1_0",
	"ped_0_1_1",
	"ped_0_1_2",
	"ped_0_1_3",
	"ped_0_1_4",
	"ped_0_1_5",
	"ped_0_1_6",
	"ped_0_1_7",
	"ped_1_0_0",
	"ped_1_0_1",
	"ped_1_0_2",
	"ped_1_0_3",
	"ped_1_0_4",
	"ped_1_0_5",
	"ped_1_0_6",
	"ped_1_0_7",
	"ped_1_1_0",
	"ped_1_1_1",
	"ped_1_1_2",
	"ped_1_1_3",
	"ped_1_1_4",
	"ped_1_1_5",
	"ped_1_1_6",
	"ped_1_1_7",
	"ped_2_0_0",
	"ped_2_0_1",
	"ped_2_0_2",
	"ped_2_0_3",
	"ped_2_0_4",
	"ped_2_0_5",
	"ped_2_0_6",
	"ped_2_0_7",
	"ped_2_1_0",
	"ped_2_1_1",
	"ped_2_1_2",
	"ped_2_1_3",
	"ped_2_1_4",
	"ped_2_1_5",
	"ped_2_1_6",
	"ped_2_1_7",
	"ped_3_0_0",
	"ped_3_0_1",
	"ped_3_0_2",
	"ped_3_0_3",
	"ped_3_0_4",
	"ped_3_0_5",
	"ped_3_0_6",
	"ped_3_0_7",
	"ped_3_1_0",
	"ped_3_1_1",
	"ped_3_1_2",
	"ped_3_1_3",
	"ped_3_1_4",
	"ped_3_1_5",
	"ped_3_1_6",
	"ped_3_1_7",
	"ped_4_0_0",
	"ped_4_0_1",
	"ped_4_0_2",
	"ped_4_0_3",
	"ped_4_0_4",
	"ped_4_0_5",
	"ped_4_0_6",
	"ped_4_0_7",
	"ped_4_1_0",
	"ped_4_1_1",
	"ped_4_1_2",
	"ped_4_1_3",
	"ped_4_1_4",
	"ped_4_1_5",
	"ped_4_1_6",
	"ped_4_1_7",
	"ped_5_0_0",
	"ped_5_0_1",
	"ped_5_0_2",
	"ped_5_0_3",
	"ped_5_0_4",
	"ped_5_0_5",
	"ped_5_0_6",
	"ped_5_0_7",
	"ped_5_1_0",
	"ped_5_1_1",
	"ped_5_1_2",
	"ped_5_1_3",
	"ped_5_1_4",
	"ped_5_1_5",
	"ped_5_1_6",
	"ped_5_1_7",
	"ped_6_0_0",
	"ped_6_0_1",
	"ped_6_0_2",
	"ped_6_0_3",
	"ped_6_0_4",
	"ped_6_0_5",
	"ped_6_0_6",
	"ped_6_0_7",
	"ped_6_1_0",
	"ped_6_1_1",
	"ped_6_1_2",
	"ped_6_1_3",
	"ped_6_1_4",
	"ped_6_1_5",
	"ped_6_1_6",
	"ped_6_1_7",
	"ped_7_0_0",
	"ped_7_0_1",
	"ped_7_0_2",
	"ped_7_0_3",
	"ped_7_0_4",
	"ped_7_0_5",
	"ped_7_0_6",
	"ped_7_0_7",
	"ped_7_1_0",
	"ped_7_1_1",
	"ped_7_1_2",
	"ped_7_1_3",
	"ped_7_1_4",
	"ped_7_1_5",
	"ped_7_1_6",
	"ped_7_1_7",
	"corpse_0_0",
	"corpse_0_1",
	"corpse_0_2",
	"corpse_0_3",
	"corpse_1_0",
	"corpse_1_1",
	"corpse_1_2",
	"corpse_1_3",
	"corpse_2_0",
	"corpse_2_1",
	"corpse_2_2",
	"corpse_2_3",
	"corpse_3_0",
	"corpse_3_1",
	"corpse_3_2",
	"corpse_3_3",
	"corpse_4_0",
	"corpse_4_1",
	"corpse_4_2",
	"corpse_4_3",
	"corpse_5_0",
	"corpse_5_1",
	"corpse_5_2",
	"corpse_5_3",
	"corpse_6_0",
	"corpse_6_1",
	"corpse_6_2",
	"corpse_6_3",
	"corpse_7_0",
	"corpse_7_1",
	"corpse_7_2",
	"corpse_7_3",
	"muzzle",
	"bullet",
	"spark",
	"blood_dot",
	"glow_red",
	"glow_blue",
	"shadow_car",
	"stain0",
	"stain1",
	"stain2",
	"stain3",
	"boom0",
	"boom1",
	"boom2",
	"boom3",
	"boom4",
	"boom5",
	"smoke0",
	"smoke1",
	"smoke2",
	"fire0",
	"fire1",
	"fire2",
	"pk_health",
	"pk_armor",
	"pk_pistol",
	"pk_smg",
	"pk_shotgun",
	"pk_cash",
	"ic_fists",
	"ic_pistol",
	"ic_smg",
	"ic_shotgun",
	"minimap",
};
#endif
